### ISSUE TITLE
Cannot enable Neptune notebook extension on Google Colab notebook

### ISSUE THREAD

**Issue by mirik123** [neptune-ai/neptune-notebooks#166]
I want to use Neptune Jupyter notebook extension in Google Colab notebook.
```
! pip install neptune-client neptune-contrib neptune-notebooks
! jupyter nbextension enable --py neptune-notebooks
Requirement already satisfied: neptune-client in /usr/local/lib/python3.7/dist-packages (0.9.16)
Requirement already satisfied: neptune-contrib in /usr/local/lib/python3.7/dist-packages (0.27.1)
Requirement already satisfied: neptune-notebooks in /usr/local/lib/python3.7/dist-packages (0.9.0)
```

The "neptune-client" itself work well, I just cannot enable Jupyter notebook extension. The following error is thrown when executing the "jupyter nbextension enable" line:
```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 896, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 872, in toggle_nbextension_python
    logger=self.log)
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 483, in enable_nbextension_python
    logger=logger)
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 380, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
ImportError: No module named neptune-notebooks
```

**Comment by Herudaio** [comment]
@mirik123 Unfortunately it's not possible to enable any extension (including Neptune's) in Google Colab. I believe it's due to security reasons.
